name: first_action
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    name: My first job
    steps:
      - name: Print greeting
        run: echo "hello world"
      - name: Say GoodBye
        run: echo "Good Bye"
